### ISSUE TITLE
util::function_traits fails with generic lambda on MSVC

### ISSUE THREAD

**Issue by xtofl** [Dobiasd/FunctionalPlus#10]
This works out of the box - great!

    auto cpp11_odd = [](int i) { return i % 2 != 0; };
    fplus::keep_if(cpp11_odd,
        generate_range<std::vector<int>>(10, 1000));

This fails with [C3556](https://msdn.microsoft.com/en-us/library/dd394161.aspx) on VS2015:

    auto cpp14_odd = [](auto i) { return i % 2 != 0; };
    fplus::keep_if(cpp14_odd,
        generate_range<std::vector<int>>(10, 1000));

[Output-Build.txt](https://github.com/Dobiasd/FunctionalPlus/files/302009/Output-Build.txt)

If that would work out of the box... great!

**Comment by Dobiasd** [comment]
Oh, very good observation. Thank you.

The reason is the call to `check_unary_predicate_for_container<Pred, Container>();` in [`fplus::keep_if`](https://github.com/Dobiasd/FunctionalPlus/blob/641dfcb18d457da6a002182dadfb260bf37d3f82/include/fplus/filter.h#L25).

To generate more readable error messages, I check if the given predicate takes something the [value_type of the container is convertible to](https://github.com/Dobiasd/FunctionalPlus/blob/641dfcb18d457da6a002182dadfb260bf37d3f82/include/fplus/compare.h#L19) and [returns something boolish](https://github.com/Dobiasd/FunctionalPlus/blob/641dfcb18d457da6a002182dadfb260bf37d3f82/include/fplus/compare.h#L22).
Deleting this line from `keep_if` makes your code compile.

I wonder if we can have the best of both worlds (generic lambda compatibility and nice compile time errors by asserts). Do you have an idea?

**Comment by Dobiasd** [comment]
As a (quite ugly, admittedly) workaround you can convert the generic lambda, at least if it holds no state, to a concrete function pointer.

	fplus::keep_if(static_cast<bool(*)(int)>(cpp14_odd),
		fplus::generate_range<std::vector<int>>(10, 1000));

or, in the case of `keep_if` do in by spcifying the first template parameter:

	fplus::keep_if<bool(*)(int)>(cpp14_odd,
		fplus::generate_range<std::vector<int>>(10, 1000));

**Comment by Dobiasd** [comment]
The workaround is no longer needed. The following code - and other situations using generic lambdas - now ([relevant commit](https://github.com/Dobiasd/FunctionalPlus/commit/aa6103c1513447ce68de8c2e6a8e3c3a98df277c)) work out of the box.

    auto cpp14_odd = [](auto i) { return i % 2 != 0; };
    fplus::keep_if(cpp14_odd,
        fplus::generate_range<std::vector<int>>(10, 1000));

Luckily it was not needed to introduce C++14 dependency for this. A C++11 compiler still suffices if one does not use generic lambdas or other C++14 features.
