### ISSUE TITLE
Logo for FunctionalPlus

### ISSUE THREAD

**Issue by Yasujizr** [Dobiasd/FunctionalPlus#154]
Hi,

I'm designing for open source projects, expanding my portfolio. I want designing an icon for your project. There are a few ideas in my mind, I hope you accept and I do them. If you have an idea, please let me know. In this way we create a icon.

Best Regards.

**Comment by Dobiasd** [comment]
Hi Yasujizr,

thanks for this offer.

So if we would have a new logo, it would be visible on the following pages:
- https://github.com/Dobiasd/FunctionalPlus/blob/master/README.md
- http://www.editgym.com/fplus-api-search/
- http://www.editgym.com/

Of course it would need to also be subject to the MIT licence, as the rest of FunctionalPlus is.

The issue is, I of course can not decide beforehand, if I would be willing to adopt a new logo, in case you design one. So if you can deal with the risk of me just saying "Meh, I'll stick with the old logo instead.", feel free to go ahead and create a proposal. :slightly_smiling_face:
