### ISSUE TITLE
Request for conda forge recipe

### ISSUE THREAD

**Issue by faysou** [Dobiasd/FunctionalPlus#161]
It would be practical if this library could be installed via conda using a conda-forge recipe.

This way it would make it easy for people using xeus-cling to use it.

**Comment by Dobiasd** [comment]
Hi faysou,

thanks for the suggestion.

I don't have any experience with Conda. Would you be interested in creating a pull request, adding whatever is required?

**Comment by faysou** [comment]
Hi Dobiasd,

I don't have experience with conda forge as well, and I don't have a high level in c++, I'm just a casual user who uses c++ sometimes for prototypes.

There are some guidelines here regarding conda-forge.
https://conda-forge.org/#add_recipe

**Comment by Dobiasd** [comment]
OK, thanks.

One question to help me better understand your motivation: Did you already get FunctionalPlus running with [one of the other ways to install](https://github.com/Dobiasd/FunctionalPlus/blob/master/INSTALL.md)?

**Comment by faysou** [comment]
Yes I did. I can also get it working in xeus cling by including the path to it, as your library is header only. I just thought providing the library in conda forge would make it even easier for people, and contribute to more people using this library.

**Comment by Dobiasd** [comment]
Thanks, understood.

Yes, supporting as many package managers as possible might be convenient for potential users. However, it also adds complexity for future releases and additional overhead for the maintainers of the library, e.g., me. :wink:

If I remember correctly, we were supporting one additional package manager in the past, but later removed it, because of all the overhead (manual work for releases) involved. However, I currently can not remember its name. Maybe it even wasn't in FunctionalPlus but in [frugally-deep](https://github.com/Dobiasd/frugally-deep).

Nevertheless, if the demand for conda is not very high, my default would be to not implement it. Do you know how common conda is for installing non-Python (especially C++) libraries?

I see [`nlohmann/json`](https://github.com/nlohmann/json) (also a header-only-C++ library) supports conda, but in its repo I can't find what they did to achieve this. Maybe it's all being done [externally](https://github.com/conda-forge/nlohmann_json-feedstock)?

**Comment by faysou** [comment]
Xtensor uses conda for distribution, as well as other projects from quantstack.
https://github.com/xtensor-stack/xtensor-blas
https://quantstack.net

This allows an easy installation in xeus cling.

**Comment by faysou** [comment]
Here is an example of where the conda forge repos are.
https://github.com/conda-forge/xtensor-blas-feedstock

**Comment by Dobiasd** [comment]
OK, it seems there is no C++ knowledge needed to create a conda recipe.

Also, one does not even need to adjust the actual library repository, everything is done externally, i.e., in [`conda-forge`](https://github.com/conda-forge).

The two examples of C++-header-only libraries look very similar:
- [`conda-forge/nlohmann_json-feedstock`](https://github.com/conda-forge/nlohmann_json-feedstock)
- [`conda-forge/xtensor-blas-feedstock`](https://github.com/conda-forge/xtensor-blas-feedstock)

[`conda-forge/staged-recipes`](https://github.com/conda-forge/staged-recipes) is "a place to submit conda recipes before they become fully fledged conda-forge feedstocks".

It also seems [well documented](https://github.com/conda-forge/staged-recipes#getting-started).

I'll give it a try.

**Comment by faysou** [comment]
Nice, good luck !

**Comment by Dobiasd** [comment]
My [PR](https://github.com/conda-forge/staged-recipes/pull/10609) was just merged. :slightly_smiling_face:

I don't know how the process will continue from now, but I guess at some point

https://github.com/conda-forge/FunctionalPlus-feedstock

will be available and

```bash
conda config --add channels conda-forge
conda install FunctionalPlus
```

should work.

Right now this is not (yet) the case.

**Comment by faysou** [comment]
That's good. I think the use of xeus cling will increase over time, and potentially of your library too.

I like functional programming, I used to work a lot in Mathematica and I almost never wrote loops in it.

**Comment by pthom** [comment]
This is very good news! This reminds me that I had written an article about Cling and I had used FunctionalPlus in the demonstrations. 
You can see the article here: [REPL (Read-Eval-Print-Loop) in C++: hands-on session](http://code-ballads.net/read-eval-print-loop-repl-in-c/)

(And you can jump directly to a xeus notebook that uses fplus here: https://mybinder.org/v2/gh/pthom/Cling_Repl_Demo/master?filepath=notebooks%2F2_Functional_REPL.ipynb )

**Comment by Dobiasd** [comment]
`conda install FunctionalPlus` is working. :tada:
