### ISSUE TITLE
Add "deleters" to functions

### ISSUE THREAD

**Issue by pfeatherstone** [Dobiasd/FunctionalPlus#166]
Use case:
I might have a container of pointers and want to use something like fplus::keep_if, but I want to apply a function when removing elements, namely a function that deletes the pointers.
For example:
```
vector<int*> a;
a = fplus::keep_if([](int* x) {return *x % 2 == 0;}, a, [](int* x) {delete x;});
```
Also, should there be versions of functions that modify in-place? Something like:
```
template <typename Pred, typename Container>
void keep_if_(Pred pred, Container& xs)
{
   /*modify in-plz d*/
...
}
```

**Comment by Kvaz1r** [comment]
Why not using smart pointer with custom deleters instead?

**Comment by pfeatherstone** [comment]
Because i'm not a fan of wrapping all my objects with smart pointers. It seems to be a recurring thing in "modern c++". It just adds complexity for the sake of it, and extra code, ya-di-ya-di-ya. Adding an extra function to ```keep_if``` seems to be much simpler.

**Comment by Dobiasd** [comment]
> I might have a container of pointers and want to use something like fplus::keep_if, but I want to apply a function when removing elements, namely a function that deletes the pointers.

In theory, we could adjust `fplus::keep_if` (and `fplus::drop_if`, etc.) to support calling a custom function with each to-be-removed object. But from a separation-of-concerns point of view, it does not look very good to me. In modern C++ the responsibility to free resources usually is implemented as [a concern of the object](https://en.cppreference.com/w/cpp/language/raii), not as a concern of multiple different pieces of code that interact with the object. This not only makes the code simpler but also helps to avoid memory leaks, especially in case of exceptions.

So, basically I'm with Kvaz1r on that. :slightly_smiling_face:

To solve your given use-case, if you really want to use raw pointers, you could use `fplus::partition`. You'll receive two new containers, one to keep, and one to iterate over and do whatever you like to the content, e.g. delete the objects the pointers are pointing to.

> Because i'm not a fan of wrapping all my objects with smart pointers. It seems to be a recurring thing in "modern c++". It just adds complexity for the sake of it, and extra code, ya-di-ya-di-ya. Adding an extra function to keep_if seems to be much simple

From my point of view, using [`std::unique_ptr`](https://en.cppreference.com/w/cpp/memory/unique_ptr) or [`std::shared_ptr`](https://en.cppreference.com/w/cpp/memory/shared_ptr) does not add complexity, but reduces complexity significantly instead. It makes the code much more simple to reason about. If I see raw pointer being used in some new code I'm reviewing, I request a good excuse, i.e. the results of profiling the application, showing that it's really needed to use raw pointers for performance. If not, I'd always push for the "modern" approach as default, because it's much more maintainable from my experience.

---

> Also, should there be versions of functions that modify in-place?

Yes, definitely. This can be quite helpful in some performance-critical situations. And that's why FunctionalPlus already support it. :sunglasses:

From the [`README.md`](https://github.com/Dobiasd/FunctionalPlus/blob/master/README.md):

```
FunctionalPlus internally often can operate in-place if a given container is an r-value (e.g. in chained calls) and thus avoid many unnecessary allocations and copies.
```

[`std::move`](https://en.cppreference.com/w/cpp/utility/move) can help here.

**Comment by pfeatherstone** [comment]
If i use shared_ptr, it forces me to manage my pointers with shared_ptr in other places, which i don't necessarily want to do. I'll think about it. Otherwise, I can just use a good old fashioned for-loop.

**Comment by Dobiasd** [comment]
> If i use shared_ptr, it forces me to manage my pointers with shared_ptr in other places

Not neccessarily, since there is [`std::shared_ptr<T>::get`](https://en.cppreference.com/w/cpp/memory/shared_ptr/get).

**Comment by pfeatherstone** [comment]
okidoki. Though i think i'll just write a quick keep_if that accepts a deleter function. It's not a lot of code and does what i need. I've been writing a lot of pure C lately (due to project requirement), which has taught me restraint when it comes to using c++ paradigms. I think I'm more of a C-with-classes type of programmer now. But still interested in what C++ has to offer, hence why i looked at this repo, (and i've used frugally-deep in the past which is awesome by the way)

**Comment by Dobiasd** [comment]
Thanks. :slightly_smiling_face:
Yes, I remember our discussions about how to improve convolution performance. :+1:
