### ISSUE TITLE
Strange picture in the project's github wiki

### ISSUE THREAD

**Issue by pthom** [Dobiasd/FunctionalPlus#204]
Hello,

It seems someone edited the wiki today and added a rather strange image. Did you notice it?

**Comment by Dobiasd** [comment]
Oh, thanks a lot. :+1: No, I did not notice it yet.

We had the following Wiki settings.

![MrvYZnp](https://i.imgur.com/MrvYZnp.png)

So everybody was free to edit it. `¯\_(ツ)_/¯`

I've changed to the following because currently, we don't need a wiki here.

![eUXj9sn](https://i.imgur.com/eUXj9sn.png)

Anyway, I've made [a screenshot of this work of art](https://i.imgur.com/Dad2uiU.png), so future people reading this issue will also have a chance to enjoy this work of art. :joy:
