### ISSUE TITLE
Migrate to Github Actions?

### ISSUE THREAD

**Issue by offa** [Dobiasd/FunctionalPlus#206]
Travis has changed it's pricing modell ([details](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)).

Short story: How about moving CI builds to Github Actions?

**Comment by Dobiasd** [comment]
Yeah, I've [head about this](https://github.com/Dobiasd/FunctionalPlus/pull/197#issuecomment-744406421). Since we're running tests on OS X, I guess the slogan on their landing page ("Testing your open source projects is always 100% free! Seriously. Always. We like to think of it as our way of giving back to a community that gives us so much as well.") does not fully apply to us. :neutral_face:

From what I've read, I'd also prefer GitHub Actions over CircleCI.

Are you interested in implementing this change? I can give you collaborator access to this repository if that helps. :slightly_smiling_face:

**Comment by offa** [comment]
Yes, I can add migrate the builds. Adding GH Actions doesn't require any permissions, it's auto-enabled with a suitable yaml configuration.

**Comment by offa** [comment]
Btw. even linux builds get only limited time for free. FOSS projects can contact the support for some more minutes, but you have to do it each time you'll need some. What a shame.

**Comment by Dobiasd** [comment]
> Btw. even linux builds get only limited time for free. FOSS projects can contact the support for some more minutes, but you have to do it each time you'll need some. What a shame.

Oh, man. Yeah, let's leave this sinking ship. :grin:

> Yes, I can add migrate the builds. Adding GH Actions doesn't require any permissions, it's auto-enabled with a suitable yaml configuration.

Awesome! :heart:

I'll then learn from this for switching [frugally-deep](https://github.com/Dobiasd/frugally-deep), [undictify](https://github.com/Dobiasd/undictify) and [enterprython](https://github.com/Dobiasd/enterprython) too.

**Comment by offa** [comment]
> I'll then learn from this for switching [frugally-deep](https://github.com/Dobiasd/frugally-deep), [undictify](https://github.com/Dobiasd/undictify) and [enterprython](https://github.com/Dobiasd/enterprython) too.

The python builds do not look too difficult to port, maybe you can get some ideas from my pipelines already (eg. [here](https://github.com/offa/trackpack/blob/master/.github/workflows/ci.yml)).

**Comment by Dobiasd** [comment]
You're right. The Python stuff is quite simple. I started with [enterprython, using your `ci.yaml` as a role model](https://github.com/Dobiasd/enterprython/pull/1), and it works fine. :+1:
