### ISSUE TITLE
FunctionalPlus does not compile with C++20 (std::result_of was removed)

### ISSUE THREAD

**Issue by dasmysh** [Dobiasd/FunctionalPlus#275]
According to [cppreference.com](https://en.cppreference.com/w/cpp/types/result_of) `std::result_of` was deprecated in C++17 and removed in C++20. To make it compile again every occurrence of `std::result_of` needs to be replaced by `std::invoke_result`.

An easy fix for C++17 forward would be:
```
std::result_of<Func(Params)>
```
becomes
```
std::invoke_result<Func, Params>
```

but a solution that also works for C++14 is probably preferred.

**Comment by Dobiasd** [comment]
The problem of `std::result_of` being deprecated already came up in [this issue](https://github.com/Dobiasd/FunctionalPlus/issues/266) and was fixed by [that commit](https://github.com/Dobiasd/FunctionalPlus/commit/0257521dac2d0fa401b7c7ab95fa14ec68abe7a9).

So there should be no `std::result_of` in the [whole FunctionalPlus code anymore](https://github.com/search?q=repo%3ADobiasd%2FFunctionalPlus%20result_of&type=code).

Which version of FunctionalPlus are you using?

**Comment by dasmysh** [comment]
Sorry, I should have searched for the issue before reporting. I used the one mentioned in the [frugally-deep installation instructions](https://github.com/Dobiasd/frugally-deep/blob/master/INSTALL.md).

**Comment by Dobiasd** [comment]
Oh, thanks a lot for the remark! :+1:

I just released [a new version](https://github.com/Dobiasd/FunctionalPlus/releases/tag/v0.2.19-p0) of `FunctionalPlus` and [updated](https://github.com/Dobiasd/frugally-deep/commit/5784f91382313b1d1d95fa7c08262f9a8c506fd0) the `frugally-deep` docs accordingly. :heavy_check_mark:
