### ISSUE TITLE
Infinite ranges - generators

### ISSUE THREAD

**Issue by sjeps** [Dobiasd/FunctionalPlus#34]
Very nice library!
I find some similarities with ranges v3 from Eric Niebler.

Strong points toward yours are being more portable and faster to compile.

Anyway i'd like some more features that are missing, such as infinite ranges and generators.
For example i would really like to do:
```
std::vector<std::string> vec = {"first", "second", "third"};
for(auto & el : fplus::zip(vec, fplus::generate_range(1))
    std::cout << el.first << " " << el. second << '\n';

// outputs:
// first 1
// second 2
// third 3
```

**Comment by Dobiasd** [comment]
Thanks for the feedback. I was thinking about infinite ranges and generators, but decided to not implement them up to now. Perhaps we can solve the problems in your use cases differently, i.e. with the currently available functionality.

The result of the example you posted can be achieved with the following code:

    std::vector<std::string> vec = {"first", "second", "third"};
    for(auto & el : fplus::enumerate(vec))
        std::cout << el.second << " " << el.first << '\n';

Do you have other typical use cases for generators in mind yet?

**Comment by sjeps** [comment]
Well, enumerate seems very helpful.. I didn't know of it..
I'd need to read all the provided functions to learn all the useful stuff. Are you taking inspiration from Haskell or Python? Should i try searching for the relevant function names of these two languages?

Also I suppose that being a functional library I should learn from other languages how to do funny stuff in a functional way (being a C++ programmer i can't appreciate the utility of "tail" or "maybe").

It could be useful to link some more examples or tutorial of other languages to better understand the functional usage of the library.

Lastly i don't have much more use cases in mind, probably because there isn't language support for yeld and other stuff like that, so I could think of use cases after using some of these tecniques.

**Comment by Dobiasd** [comment]
My main inspiration comes from Haskell and [Elm](elm-lang.org).

But instead of searching for functions there, I suggest you try out the [FunctionPlus API search](http://www.editgym.com/fplus-api-search/).

If you for example need a function to concatenate a vector of strings with some delimiter string, you can search for the type of this hypothetical function (vector<string>, string) -> string and you will find fplus::join that does exactly what you want. In this functional style, the type signature of the function often is enough to deduce what the function does. :)

---

But I understand very well that functional thinking can be quite unfamiliar if you come from an imperative background. I went through the same transformation. In case you are interested, I wrote [an article about my experience back then](https://github.com/Dobiasd/articles/blob/master/switching_from_imperative_to_functional_programming_with_games_in_Elm.md).

`tail` is btw. something that is not used very often in daily work with functional languages. `maybe` on the other hand is.

---

A few tutorials about using `fplus` to solve problems functionally sounds like a very good idea. Perhaps one could use `fplus` to solve basic exercises from [hackerrank](https://www.hackerrank.com/) or somethink alike and explain the process.

Is this something you would be interested in contributing. It could be a very good exercise for you and of course it would help other learners a lot.

**Comment by sjeps** [comment]
I don't think I'll have time to help... sorry.
Anyway I'm having mixed results with the API search:
searching for:

[a] -> [(Int, a)]

will return "enumerate" very low in the rankings

**Comment by Dobiasd** [comment]
No problem, your feedback already is helpful. :)

Especially the problem with the search for `[a] -> [(Int, a)]` seems to be a bug in the matching algorithm. I will have a deeper look at it.

**Comment by Dobiasd** [comment]
@sjeps OK, this is [fixed](https://github.com/Dobiasd/FunctionalPlus/commit/0afd93dc8288a28bb06a41e0e2e64e10c9b8f1cd) now. You will find `enumerate` as expected with `[a] -> [(Int, a)]`.
