### ISSUE TITLE
Use doxygen

### ISSUE THREAD

**Issue by TurpentineDistillery** [Dobiasd/FunctionalPlus#74]
The API-search is neat, but not very useful, because a new user is in a situation "i don't know what I'm looking for". Instead, the user must have a facility to explore the library. I'd recommend annotating public API with doxy-comments and generate documentation from that.

**Comment by Dobiasd** [comment]
I like the vision of having all functions documented like that, although I do not have experience with setting doxygen up for a project yet. Do you think using an integration service like [codedocs](https://codedocs.xyz/) would be a good idea?

**Comment by TurpentineDistillery** [comment]
To be honest, I'm not sure about the exact steps either; I just know that it's possible : )
e.g.  see https://nlohmann.github.io/json/
If there are any difficulties with figuring this out, I'm sure Niels will be happy to advise.

**Comment by Dobiasd** [comment]
I experimented a bit with writing doxygen annotations. As far as I see, it is generally wished to have every parameter described separately. However in case of FunctionalPlus this seems often to lead to very trivial annotation, like in the example of `get_from_map_with_def`:

    get_from_map_with_def : (Map key val, val, key) -> val
    fwd::get_from_map_with_def : (Map key val, val) -> key -> val
    Returns the value of a key if key is present.
    Otherwise returns the provided default.

    template <typename MapType,
        typename Key = typename MapType::key_type,
        typename Val = typename MapType::mapped_type>
    Val get_from_map_with_def(const MapType& map, const Val& defVal,
        const Key& key)

A corresponding doxygen annotation could be:

    /**
     * Returns the value of a key if key is present, otherwise returns the provided default.
     * @param map the dictionary
     * @param defVal the default value
     * @param key the key
     * @return the value
     */

But the three `@param` lines bother me, since they do not provide new information, but redundant optical noise instead. Do you (or does anybody else reading this) have an idea how to circumvent this? Just leave the parameter descriptions in cases like the above?

**Comment by TurpentineDistillery** [comment]
I rarely annotate params or return. Most of my annotations are just \brief one-liners. If some argument is subject to certain non-obvious preconditions, or a template that needs to satisfy certain non-obvious requirements, then you'd document it.

Having said that, I'm accustomed to seeing annotations that document everything and provide zero information value. I don't know why.

**Comment by Dobiasd** [comment]
That approach seems reasonable. I will see what I can do without introducing too much overhead.

**Comment by Dobiasd** [comment]
Do you have a special format in mind for exploring the library using doxygen? Anything more than a list of all available functions?

I'm asking, because for the api-search I already generate [api_search/frontend/src/Database.elm](https://gist.github.com/Dobiasd/7d5e36a98cf3489903c661cae23a782a) using [api_search/parse_source_files.cpp](https://github.com/Dobiasd/FunctionalPlus/blob/master/api_search/parse_source_files.cpp) and could easily generate another website (without searching capabilities) based on it.

**Comment by TurpentineDistillery** [comment]
That would work as well. It would be reasonable to autogenerate docs from Database.elm in the short term, and maybe switch to doxygen down the line when/if you feel like it.

**Comment by Dobiasd** [comment]
OK, great. Then [this](https://github.com/Dobiasd/FunctionalPlus/commit/a3fe61f36f2b58f181d27588df1497abb9bd4be0) should do the trick for now. :)

**Comment by TurpentineDistillery** [comment]
Neat!
